dist: xenial
language: python
python:
  - "3.7"

install:
  - pip3 install  --upgrade pip
  - pip3 install  --upgrade --requirement requirements.txt

script:
  - python3 tests/test.py



after_success:
    - echo $SSH_PRIVATE_KEY | base64 -d > ssh_key
    - eval "$(ssh-agent -s)"
    - chmod 600 ssh_key
    - ssh-add ssh_key



deploy:
  - provider: script
    skip_cleanup: true
    script: ENVIRONMENT=PROD ssh -o StrictHostKeyChecking=no -i ssh_key $USER@$SERVER -p $PORT 'bash -s' < deploy-prod.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ENVIRONMENT=DEV ssh -o StrictHostKeyChecking=no -i ssh_key $USER@$SERVER -p $PORT 'bash -s' < deploy-dev.sh
    on:
      branch: DEV
