dist: xenial
language: python
python:
  - "3.7"

install:
  - pip3 install  --upgrade pip
  - pip3 install  --upgrade --requirement requirements.txt

script:
  - python3 tests/test.py



after_success:
    - echo $SSH_PRIVATE_KEY | base64 -d > ssh_key
    - chmod 400 ssh_key
    - ssh -o StrictHostKeyChecking=no -i ssh_key $USER@$SERVER -p $PORT 'bash -s' < deploy.sh
